ARG BUILDER_IMAGE
FROM $BUILDER_IMAGE as builder
WORKDIR /workspace

RUN --mount=type=bind,rw,target=. \
    hack/build-mariner-based-imgs/slim-build.sh /build \
      cmd/virt-exportproxy


FROM mcr.microsoft.com/azurelinux/base/core:3.0

RUN tdnf install -y azurelinux-repos-preview
RUN  tdnf -y install \
  ca-certificates \
  shadow-utils \
  tar \
  && tdnf clean all

RUN  adduser -u 1001 --create-home -s /bin/bash virt-exportproxy
USER 1001

COPY --from=builder /build/_out/cmd/virt-exportproxy/virt-exportproxy /usr/bin/

RUN ls /usr/bin/virt-exportproxy

ENTRYPOINT [ "/usr/bin/virt-exportproxy" ]
