// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source manager.go -package=virtwrap -destination=generated_mock_manager.go
//

// Package virtwrap is a generated GoMock package.
package virtwrap
