load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["node-labeller.go"],
    importpath = "kubevirt.io/kubevirt/cmd/node-labeller",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "node-labeller",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
